# Generated by Django 5.0.1 on 2024-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='vapi_call_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
